name: generate-ascii-artwork
on:
    push
jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: install cowsay
          run: sudo apt-get install -y cowsay
        - name: execute cowsay command
          run: cowsay -f dragon "Run for cover, I am a dragon ... RAWR" > dragon.txt
        - name: Check if file exists
          run: grep -i dragon.txt
        - name: List and Read Files
          run: ls -ltra